// Builds the loadable extension from manifest.template.json and the repo's .env.
//   node extension/scripts/configure.mjs
// Writes manifest.json (the app's address filled in) and config.js (the app address, the extension token and the
// Vercel bypass secret). Both are git-ignored: config.js holds secrets. Chrome loads the extension/ folder itself.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const extensionDir = path.resolve(here, "..");
const repoRoot = path.resolve(extensionDir, "..");

const env = Object.fromEntries(
  fs
    .readFileSync(path.join(repoRoot, ".env"), "utf8")
    .split(/\r?\n/)
    .filter((line) => line.trim() && !line.trim().startsWith("#") && line.includes("="))
    .map((line) => {
      const i = line.indexOf("=");
      return [line.slice(0, i).trim(), line.slice(i + 1).trim().replace(/^["']|["']$/g, "")];
    }),
);

const missing = ["APP_URL", "EXTENSION_TOKEN", "VERCEL_BYPASS_SECRET"].filter((key) => !env[key]);
if (missing.length) {
  console.error(`Missing in .env: ${missing.join(", ")}`);
  process.exit(1);
}

const origin = new URL(env.APP_URL).origin;
const manifest = fs.readFileSync(path.join(extensionDir, "manifest.template.json"), "utf8").replaceAll("__APP_ORIGIN__", origin);
fs.writeFileSync(path.join(extensionDir, "manifest.json"), manifest);
fs.writeFileSync(
  path.join(extensionDir, "config.js"),
  "// Generated by scripts/configure.mjs from the repo's .env. Git-ignored: it holds secrets.\n" +
    `export const CONFIG = ${JSON.stringify({ appUrl: origin, token: env.EXTENSION_TOKEN, bypass: env.VERCEL_BYPASS_SECRET })};\n`,
);
console.log(`Configured for ${origin}.`);
console.log(`Load this folder in chrome://extensions (Developer mode > Load unpacked): ${extensionDir}`);
