"""keep player games match odds forecasts and absences

Revision ID: 3ce433a96bed
Revises: fd89c678d11e
Create Date: 2026-10-08 14:40:00.952611
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ce433a96bed'
down_revision: Union[str, Sequence[str], None] = 'fd89c678d11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ff_id', sa.String(length=32), nullable=False),
    sa.Column('player', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('back', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_absences', schema=None) as batch_op:
        batch_op.create_index('ix_player_absences_ff_id_first_seen', ['ff_id', 'first_seen'], unique=False)
        batch_op.create_index('ix_player_absences_player_first_seen', ['player', 'first_seen'], unique=False)

    op.create_table('player_games',
    sa.Column('player', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('competition', sa.String(length=100), nullable=False),
    sa.Column('home', sa.String(length=160), nullable=True),
    sa.Column('away', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('mins', sa.Integer(), nullable=True),
    sa.Column('yellow', sa.Integer(), nullable=True),
    sa.Column('red', sa.Boolean(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ff_start', sa.Float(), nullable=True),
    sa.Column('sorare_start', sa.Float(), nullable=True),
    sa.Column('sofix_start', sa.Float(), nullable=True),
    sa.Column('ff_xi', sa.Boolean(), nullable=True),
    sa.Column('sofix_x', sa.Float(), nullable=True),
    sa.Column('sorare_x', sa.Float(), nullable=True),
    sa.Column('said_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('player', 'game_id')
    )
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.create_index('ix_player_games_player_date', ['player', 'date'], unique=False)

    op.create_table('match_forecasts',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('p_home', sa.Float(), nullable=False),
    sa.Column('p_draw', sa.Float(), nullable=False),
    sa.Column('p_away', sa.Float(), nullable=False),
    sa.Column('xg_home', sa.Float(), nullable=False),
    sa.Column('xg_away', sa.Float(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_table('match_odds',
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home', sa.String(length=160), nullable=False),
    sa.Column('away', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('hg', sa.Integer(), nullable=True),
    sa.Column('ag', sa.Integer(), nullable=True),
    sa.Column('odds_h', sa.Float(), nullable=True),
    sa.Column('odds_d', sa.Float(), nullable=True),
    sa.Column('odds_a', sa.Float(), nullable=True),
    sa.Column('odds_pre_h', sa.Float(), nullable=True),
    sa.Column('odds_pre_d', sa.Float(), nullable=True),
    sa.Column('odds_pre_a', sa.Float(), nullable=True),
    sa.Column('over_2_5', sa.Float(), nullable=True),
    sa.Column('which', sa.String(length=32), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('season', 'date', 'home', 'away', 'source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_odds')
    op.drop_table('match_forecasts')
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.drop_index('ix_player_games_player_date')

    op.drop_table('player_games')
    with op.batch_alter_table('player_absences', schema=None) as batch_op:
        batch_op.drop_index('ix_player_absences_player_first_seen')
        batch_op.drop_index('ix_player_absences_ff_id_first_seen')

    op.drop_table('player_absences')
    # ### end Alembic commands ###
