"""baseline schema

Revision ID: 5c4cbb29092d
Revises: 
Create Date: 2026-09-14 03:05:16.627991
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c4cbb29092d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('source_entity_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'source', 'source_name')
    )
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('promoted_flag', sa.Boolean(), nullable=False),
    sa.Column('promoted_from_tier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_fixture_id', sa.String(length=128), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('referee_name', sa.String(length=160), nullable=True),
    sa.Column('postponed_flag', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_kickoff_utc'), ['kickoff_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_matchday'), ['matchday'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_source_fixture_id'), ['source_fixture_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=180), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position_group', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('market_value_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('absence_reason', sa.String(length=160), nullable=True),
    sa.Column('injury_type', sa.String(length=160), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('p_available', sa.Float(), nullable=True),
    sa.Column('p_start_if_available', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_snapshots_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_snapshots_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_snapshots_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_snapshots_snapshot_ts'), ['snapshot_ts'], unique=False)

    op.create_table('context_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('prediction_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rest_days', sa.Float(), nullable=True),
    sa.Column('matches_last_7d', sa.Integer(), nullable=True),
    sa.Column('matches_last_14d', sa.Integer(), nullable=True),
    sa.Column('matches_last_21d', sa.Integer(), nullable=True),
    sa.Column('travel_km', sa.Float(), nullable=True),
    sa.Column('travel_km_last_7d', sa.Float(), nullable=True),
    sa.Column('europe_midweek_flag', sa.Boolean(), nullable=True),
    sa.Column('cup_midweek_flag', sa.Boolean(), nullable=True),
    sa.Column('days_to_next_match', sa.Float(), nullable=True),
    sa.Column('derby_flag', sa.Boolean(), nullable=True),
    sa.Column('title_race_flag', sa.Boolean(), nullable=True),
    sa.Column('relegation_race_flag', sa.Boolean(), nullable=True),
    sa.Column('manager_change_30d', sa.Boolean(), nullable=True),
    sa.Column('manager_tenure_days', sa.Integer(), nullable=True),
    sa.Column('squad_minutes_retained_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_snapshots_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_snapshots_prediction_ts'), ['prediction_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_snapshots_team_id'), ['team_id'], unique=False)

    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('perspective_team_id', sa.Integer(), nullable=False),
    sa.Column('prediction_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['perspective_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_snapshots_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_snapshots_perspective_team_id'), ['perspective_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_snapshots_prediction_ts'), ['prediction_ts'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bookmaker', sa.String(length=80), nullable=False),
    sa.Column('home_decimal', sa.Float(), nullable=True),
    sa.Column('draw_decimal', sa.Float(), nullable=True),
    sa.Column('away_decimal', sa.Float(), nullable=True),
    sa.Column('home_prob', sa.Float(), nullable=True),
    sa.Column('draw_prob', sa.Float(), nullable=True),
    sa.Column('away_prob', sa.Float(), nullable=True),
    sa.Column('overround', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_snapshots_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_snapshot_ts'), ['snapshot_ts'], unique=False)

    op.create_table('player_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('minutes_played', sa.Float(), nullable=True),
    sa.Column('goals', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_team_id'), ['team_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('perspective_team_id', sa.Integer(), nullable=False),
    sa.Column('prediction_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('p_win', sa.Float(), nullable=False),
    sa.Column('p_draw', sa.Float(), nullable=False),
    sa.Column('p_loss', sa.Float(), nullable=False),
    sa.Column('expected_points', sa.Float(), nullable=False),
    sa.Column('difficulty_score', sa.Float(), nullable=False),
    sa.Column('difficulty_label', sa.String(length=32), nullable=False),
    sa.Column('difficulty_percentile', sa.Float(), nullable=True),
    sa.Column('p_clean_sheet', sa.Float(), nullable=True),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['perspective_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'perspective_team_id', 'model_version')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_perspective_team_id'), ['perspective_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_prediction_ts'), ['prediction_ts'], unique=False)

    op.create_table('team_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Float(), nullable=True),
    sa.Column('shots_on_target', sa.Float(), nullable=True),
    sa.Column('corners', sa.Float(), nullable=True),
    sa.Column('fouls', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Float(), nullable=True),
    sa.Column('red_cards', sa.Float(), nullable=True),
    sa.Column('possession_pct', sa.Float(), nullable=True),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('npxg_for', sa.Float(), nullable=True),
    sa.Column('npxg_against', sa.Float(), nullable=True),
    sa.Column('xpts', sa.Float(), nullable=True),
    sa.Column('ppda', sa.Float(), nullable=True),
    sa.Column('pressures', sa.Float(), nullable=True),
    sa.Column('pre_match_elo', sa.Float(), nullable=True),
    sa.Column('post_match_elo', sa.Float(), nullable=True),
    sa.Column('rest_days', sa.Float(), nullable=True),
    sa.Column('travel_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id')
    )
    with op.batch_alter_table('team_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_match_stats_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_match_stats_team_id'), ['team_id'], unique=False)

    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_lead_hours', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_snapshots_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_snapshot_ts'), ['snapshot_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_snapshot_ts'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_available_at'))

    op.drop_table('weather_snapshots')
    with op.batch_alter_table('team_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_match_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_match_stats_fixture_id'))

    op.drop_table('team_match_stats')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_prediction_ts'))
        batch_op.drop_index(batch_op.f('ix_predictions_perspective_team_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_fixture_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('player_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_fixture_id'))

    op.drop_table('player_match')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_snapshot_ts'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_available_at'))

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_prediction_ts'))
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_perspective_team_id'))
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_fixture_id'))

    op.drop_table('feature_snapshots')
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_snapshots_team_id'))
        batch_op.drop_index(batch_op.f('ix_context_snapshots_prediction_ts'))
        batch_op.drop_index(batch_op.f('ix_context_snapshots_fixture_id'))

    op.drop_table('context_snapshots')
    with op.batch_alter_table('availability_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_snapshots_snapshot_ts'))
        batch_op.drop_index(batch_op.f('ix_availability_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_availability_snapshots_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_availability_snapshots_available_at'))

    op.drop_table('availability_snapshots')
    op.drop_table('players')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_source_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_season'))
        batch_op.drop_index(batch_op.f('ix_fixtures_matchday'))
        batch_op.drop_index(batch_op.f('ix_fixtures_kickoff_utc'))
        batch_op.drop_index(batch_op.f('ix_fixtures_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_away_team_id'))

    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('stadiums')
    op.drop_table('source_entity_map')
    op.drop_table('competitions')
    # ### end Alembic commands ###
