"""drop weather snapshots

Revision ID: 66529b836e07
Revises: a3c5e1f7b2d4
Create Date: 2026-09-16 10:31:19.387996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66529b836e07'
down_revision: Union[str, Sequence[str], None] = 'a3c5e1f7b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_available_at'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_snapshot_ts'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('forecast_lead_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('apparent_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitation_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed_kmh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('weather_snapshots_fixture_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_snapshots_pkey')),
    sa.UniqueConstraint('fixture_id', name=op.f('uq_weather_snapshots_fixture_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_weather_snapshots_snapshot_ts'), 'weather_snapshots', ['snapshot_ts'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_available_at'), 'weather_snapshots', ['available_at'], unique=False)
    # ### end Alembic commands ###
