"""sorare forecasts kept per gameweek

Revision ID: fd89c678d11e
Revises: c4e8a1b2d3f5
Create Date: 2026-09-23 17:59:22.848474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd89c678d11e'
down_revision: Union[str, Sequence[str], None] = 'c4e8a1b2d3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorare_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=100), nullable=False),
    sa.Column('gameweek', sa.String(length=100), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('projection', sa.Float(), nullable=True),
    sa.Column('plays_odds', sa.Float(), nullable=True),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('p_play', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player', 'gameweek', name='uq_sorare_forecasts_player_gameweek')
    )
    op.create_index(op.f('ix_sorare_forecasts_lock'), 'sorare_forecasts', ['lock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sorare_forecasts_lock'), table_name='sorare_forecasts')
    op.drop_table('sorare_forecasts')
    # ### end Alembic commands ###
