/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixture-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture Grid */
        get: operations["fixture_grid_api_fixture_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Refresh */
        post: operations["start_refresh_api_admin_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/refresh/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh Latest */
        get: operations["refresh_latest_api_admin_refresh_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[FixtureGrid] */
        ApiResponse_FixtureGrid_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["FixtureGrid"] | null;
            /** Error */
            error?: string | null;
            meta?: components["schemas"]["GridMeta"] | null;
        };
        /** ApiResponse[RefreshStatus] */
        ApiResponse_RefreshStatus_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["RefreshStatus"] | null;
            /** Error */
            error?: string | null;
            meta?: components["schemas"]["GridMeta"] | null;
        };
        /**
         * CellMarket
         * @description Bookmaker consensus for this team's side of the fixture, as fair probabilities (margin removed).
         *     Result from win/draw/loss prices; goal markets from the goal rates that reproduce the prices.
         */
        CellMarket: {
            /** Win */
            win: number;
            /** Draw */
            draw: number;
            /** Loss */
            loss: number;
            /** Scores */
            scores: number;
            /** Scores 2Plus */
            scores_2plus: number;
            /** Clean Sheet */
            clean_sheet: number;
            /** Concedes 2Plus */
            concedes_2plus: number;
            /** Both Score */
            both_score: number;
            /** Expected Points */
            expected_points: number;
            /** Bookmakers */
            bookmakers: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** CellPrediction */
        CellPrediction: {
            /** Difficulty */
            difficulty: number;
            /**
             * Label
             * @enum {string}
             */
            label: "Very favourite" | "Favourite" | "Even" | "Underdog" | "Big underdog";
            /**
             * Bucket
             * @enum {integer}
             */
            bucket: 1 | 2 | 3 | 4 | 5;
            /** Expected Points */
            expected_points: number;
            probabilities: components["schemas"]["Prob"];
            /** Clean Sheet */
            clean_sheet: number | null;
            /** Xg For */
            xg_for: number | null;
            /** Xg Against */
            xg_against: number | null;
            /** Both Score */
            both_score?: number | null;
        };
        /**
         * CellRecord
         * @description How this club has done before at the price this fixture gives it.
         *
         *     Counted from bookmaker closing odds over the last five seasons, because those are the only record of
         *     what a club *was* priced at. `edge` is the club's rate minus the league's at the same price, shrunk
         *     toward 0 by sample size - what it adds to its billing, rather than the billing itself.
         */
        CellRecord: {
            /** Band */
            band: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Rate */
            rate: number;
            /** League */
            league: number;
            /** Edge */
            edge: number;
        };
        /** CellResult */
        CellResult: {
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "W" | "D" | "L";
        };
        /**
         * CellReview
         * @description How the forecast did, once the game was played.
         *
         *     The forecast is the last one made before kickoff, whatever model version wrote it: the point is what the
         *     board said at the time. `surprise` comes from services/postmortem.py.
         */
        CellReview: {
            /** Outcome Chance */
            outcome_chance: number;
            /** Points */
            points: number;
            /** Expected Points */
            expected_points: number;
            /** Surprise */
            surprise: number;
        };
        /** FixtureGrid */
        FixtureGrid: {
            /** Season */
            season: string;
            /** Current Matchday */
            current_matchday: number | null;
            /** Model Version */
            model_version: string | null;
            lens_scales: components["schemas"]["LensScales"];
            /** Matchdays */
            matchdays: components["schemas"]["GridMatchday"][];
            /** Teams */
            teams: components["schemas"]["GridTeam"][];
        };
        /** GridCell */
        GridCell: {
            /** Fixture Id */
            fixture_id: number;
            /** Opponent Code */
            opponent_code: string;
            /**
             * Venue
             * @enum {string}
             */
            venue: "H" | "A";
            /**
             * Kickoff Utc
             * Format: date-time
             */
            kickoff_utc: string;
            /** Date Confirmed */
            date_confirmed: boolean;
            /** Rescheduled */
            rescheduled: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "live" | "finished" | "postponed";
            result: components["schemas"]["CellResult"] | null;
            review?: components["schemas"]["CellReview"] | null;
            prediction: components["schemas"]["CellPrediction"] | null;
            market?: components["schemas"]["CellMarket"] | null;
            record?: components["schemas"]["CellRecord"] | null;
            record_price?: components["schemas"]["CellRecord"] | null;
        };
        /** GridMatchday */
        GridMatchday: {
            /** Number */
            number: number;
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** Finished */
            finished: boolean;
        };
        /** GridMeta */
        GridMeta: {
            /** Last Synced At */
            last_synced_at: string | null;
            /** Last Predicted At */
            last_predicted_at: string | null;
            /**
             * Model Notes
             * @default []
             */
            model_notes: components["schemas"]["ModelNote"][];
        };
        /** GridTeam */
        GridTeam: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Crest Url */
            crest_url: string | null;
            /** Cells */
            cells: components["schemas"]["GridCell"][][];
            /** Opening */
            opening?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LensScale
         * @description Four cut points splitting a lens into buckets 1 (easiest) … 5 (hardest).
         *
         *     higher_is_easier=False (overall difficulty): bucket = 1 + number of cuts the value exceeds.
         *     higher_is_easier=True (xG, clean sheet, market win chance): cuts are descending; bucket = 1 + number of cuts the value is below.
         */
        LensScale: {
            /** Cuts */
            cuts: number[];
            /** Higher Is Easier */
            higher_is_easier: boolean;
        };
        /**
         * LensScales
         * @description One scale per lens (named fields rather than a dict, so clients get a typed object).
         */
        LensScales: {
            overall: components["schemas"]["LensScale"];
            attack: components["schemas"]["LensScale"];
            defence: components["schemas"]["LensScale"];
            odds: components["schemas"]["LensScale"];
            record: components["schemas"]["LensScale"];
            market_record: components["schemas"]["LensScale"];
        };
        /** ModelNote */
        ModelNote: {
            /** Lens */
            lens: ("overall" | "attack" | "defence") | null;
            /** Text */
            text: string;
        };
        /** Prob */
        Prob: {
            /** Win */
            win: number;
            /** Draw */
            draw: number;
            /** Loss */
            loss: number;
        };
        /** RefreshRunOut */
        RefreshRunOut: {
            /** Id */
            id: number;
            /** Trigger */
            trigger: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "abandoned";
            /** Step */
            step: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Steps */
            steps: {
                [key: string]: "succeeded" | "failed";
            };
        };
        /** RefreshStatus */
        RefreshStatus: {
            run: components["schemas"]["RefreshRunOut"] | null;
            /** Retry After */
            retry_after: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fixture_grid_api_fixture_grid_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_FixtureGrid_"];
                };
            };
        };
    };
    start_refresh_api_admin_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RefreshStatus_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_latest_api_admin_refresh_latest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RefreshStatus_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
